repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/kieran-ryan/pyprojectsort
    rev: v0.3.0
    hooks:
      - id: pyprojectsort
  - repo: https://github.com/asmeurer/removestar
    rev: "1.5.1"
    hooks:
      - id: removestar
        args: [--in-place, pyprojectsort]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.7.0"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [--configfile=pyproject.toml, --severity-level=medium, .]
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.15.2
    hooks:
      - id: cspell
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
